### ISSUE TITLE
Tests fail with old Spreadsheet::Reader::Format

### ISSUE THREAD

**Issue by eserte** [jandrew/p5-spreadsheet-reader-excelxml#2]
Another problem: on some of my smokers all tests fail (test reports are not yet at CPAN Testers, but will appear in a few hours). This seems to depend on the installed Spreadsheet::Reader::Format version (negative theta means that there were fails):
```
****************************************************************
Regression 'mod:Spreadsheet::Reader::Format'
****************************************************************
Name                   Theta          StdErr     T-stat
[0='const']           1.0000          0.0000    27453536990976280.00
[1='eq_v0.2.6']      -1.0000          0.0000    -18754336126532300.00
[2='eq_v0.2.8']       0.0000          0.0000       0.00

R^2= 1.000, N= 34, K= 3
****************************************************************
```

**Comment by jandrew** [comment]
That seems easy enough to fix.  I will set a minimum requirement for Spreadsheet::Reader::Format and re-release.

**Comment by jandrew** [comment]
The analysis was really helpful.  I would not have root caused it so quick without that.
