### ISSUE TITLE
Synopsis fix

### ISSUE THREAD

**Issue by delskorch** [jandrew/p5-spreadsheet-reader-excelxml#6]
Your synopsis example fails because the col loop reads into EOR

```
for my $row ( $row_min .. $row_max ) {
                for my $col ( $col_min .. $col_max ) {
```

should be

```
or my $row ( $row_min .. $row_max - 1) {
                for my $col ( $col_min .. $col_max - 1 ) {
```

or perhaps count_from_zero => 0 would fix it 

`my $parser   = Spreadsheet::Reader::ExcelXML->new( count_from_zero => 0 )`

**Comment by jandrew** [comment]
Thank you for the catch.  Let me see what I can do.

**Comment by jandrew** [comment]
@delskorch I can't seem to duplicate your problem.  Are you passing any flags when you call 

    use Spreadsheet::Reader::ExcelXML;

Maybe you could share a larger code segment.  The other possibility is there may be some system incompatibilities.

**Comment by jandrew** [comment]
Closing with an added test since no current response from the OP.

**Comment by jandrew** [comment]
I am re-opening this issue since the coverage test added is failing for free bsd perls 5.22.1 and 5.22.2.  The reports are not showing exactly the same behavior as reported in the OP.

**Comment by jandrew** [comment]
OK it looks like the free bsd versions are now passing with v0.12.2.  I will leave this open for a few more days to see if any other unusual fails occur.  After that I'm closing the issue for good.

**Comment by jandrew** [comment]
Release v0.12.2 does appear to fix the failing free bsd issues.  New fails should be logged under a new issue.
